# Generated by Django 6.0.6 on 2026-07-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalHouseboatDataset500Rows',
            fields=[
                ('houseboatid', models.TextField(db_column='HouseboatID', primary_key=True, serialize=False)),
                ('houseboatname', models.TextField(blank=True, db_column='HouseboatName', null=True)),
                ('location', models.TextField(blank=True, db_column='Location', null=True)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('priceinr', models.IntegerField(blank=True, db_column='PriceINR', null=True)),
                ('season', models.TextField(blank=True, db_column='Season', null=True)),
                ('bedrooms', models.IntegerField(blank=True, db_column='Bedrooms', null=True)),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
                ('ac', models.TextField(blank=True, db_column='AC', null=True)),
                ('luxury', models.TextField(blank=True, db_column='Luxury', null=True)),
                ('rating', models.FloatField(blank=True, db_column='Rating', null=True)),
                ('reviewcount', models.IntegerField(blank=True, db_column='ReviewCount', null=True)),
                ('bookingcount', models.IntegerField(blank=True, db_column='BookingCount', null=True)),
                ('food', models.TextField(blank=True, db_column='Food', null=True)),
                ('wifi', models.TextField(blank=True, db_column='WiFi', null=True)),
                ('tv', models.TextField(blank=True, db_column='TV', null=True)),
                ('jacuzzi', models.TextField(blank=True, db_column='Jacuzzi', null=True)),
                ('fishing', models.TextField(blank=True, db_column='Fishing', null=True)),
                ('canoeing', models.TextField(blank=True, db_column='Canoeing', null=True)),
                ('upperdeck', models.TextField(blank=True, db_column='UpperDeck', null=True)),
                ('parking', models.TextField(blank=True, db_column='Parking', null=True)),
                ('petfriendly', models.TextField(blank=True, db_column='PetFriendly', null=True)),
                ('triptype', models.TextField(blank=True, db_column='TripType', null=True)),
                ('suitablefor', models.TextField(blank=True, db_column='SuitableFor', null=True)),
                ('availability', models.TextField(blank=True, db_column='Availability', null=True)),
                ('imagefile', models.TextField(blank=True, db_column='ImageFile', null=True)),
            ],
            options={
                'db_table': 'professional_houseboat_dataset_500_rows',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Houseboat',
        ),
    ]
