# Generated by Django 6.0.6 on 2026-07-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='houseboat',
            field=models.CharField(db_column='houseboat_id', max_length=20),
        ),
    ]
